### ISSUE TITLE
use of enum 'lightStatus_t' without previous declaration

### ISSUE THREAD

**Issue by tatasker** [CelliesProjects/aquacontrol32#9]
I keep running into this error and searching the web for a solution but to know avail.

I am using Arduino IDE 1.8.7 (Windows Store 1.18.15) and the latest version of Aquacontrol32.

Below is the error message log.

Arduino: 1.8.7 (Windows Store 1.8.15.0) (Windows 10), Board: "LOLIN D32, Default, 80MHz, 921600, None"

aquacontrol32:114:6: error: use of enum 'lightStatus_t' without previous declaration

 enum lightStatus_t

      ^

aquacontrol32:119:39: error: 'lightStatus_t' does not name a type

 const char lightStatusToString( const lightStatus_t status )

                                       ^

aquacontrol32:119:60: error: two or more data types in declaration of 'lightStatusToString'

 const char lightStatusToString( const lightStatus_t status )

                                                            ^

aquacontrol32:115:1: error: expected unqualified-id before '{' token

 {

 ^

aquacontrol32:119:39: error: 'lightStatus_t' does not name a type

 const char lightStatusToString( const lightStatus_t status )

                                       ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\aquacontrol32.ino: In function 'const char lightStatusToString(int)':

aquacontrol32:123:10: error: 'LIGHTS_OFF' was not declared in this scope

     case LIGHTS_OFF:   return PSTR(" LIGHTS OFF");

          ^

In file included from C:\Users\Tom\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\cores\esp32/WString.h:29:0,

                 from C:\Users\Tom\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\cores\esp32/Arduino.h:150,

                 from sketch\aquacontrol32.ino.cpp:1:

C:\Users\Tom\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\cores\esp32/pgmspace.h:36:25: error: invalid conversion from 'const char*' to 'char' [-fpermissive]

 #define PSTR(s)       (s)

                         ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\aquacontrol32.ino:123:31: note: in expansion of macro 'PSTR'

     case LIGHTS_OFF:   return PSTR(" LIGHTS OFF");

                               ^

aquacontrol32:124:10: error: 'LIGHTS_ON' was not declared in this scope

     case LIGHTS_ON:    return PSTR(" LIGHTS ON ");

          ^

In file included from C:\Users\Tom\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\cores\esp32/WString.h:29:0,

                 from C:\Users\Tom\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\cores\esp32/Arduino.h:150,

                 from sketch\aquacontrol32.ino.cpp:1:

C:\Users\Tom\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\cores\esp32/pgmspace.h:36:25: error: invalid conversion from 'const char*' to 'char' [-fpermissive]

 #define PSTR(s)       (s)

                         ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\aquacontrol32.ino:124:31: note: in expansion of macro 'PSTR'

     case LIGHTS_ON:    return PSTR(" LIGHTS ON ");

                               ^

aquacontrol32:125:10: error: 'LIGHTS_AUTO' was not declared in this scope

     case LIGHTS_AUTO:  return PSTR("LIGHTS AUTO");

          ^

In file included from C:\Users\Tom\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\cores\esp32/WString.h:29:0,

                 from C:\Users\Tom\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\cores\esp32/Arduino.h:150,

                 from sketch\aquacontrol32.ino.cpp:1:

C:\Users\Tom\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\cores\esp32/pgmspace.h:36:25: error: invalid conversion from 'const char*' to 'char' [-fpermissive]

 #define PSTR(s)       (s)

                         ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\aquacontrol32.ino:125:31: note: in expansion of macro 'PSTR'

     case LIGHTS_AUTO:  return PSTR("LIGHTS AUTO");

                               ^

C:\Users\Tom\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\cores\esp32/pgmspace.h:36:25: error: invalid conversion from 'const char*' to 'char' [-fpermissive]

 #define PSTR(s)       (s)

                         ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\aquacontrol32.ino:126:31: note: in expansion of macro 'PSTR'

     default:           return PSTR(" UNDEFINED ");

                               ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\aquacontrol32.ino: At global scope:

aquacontrol32:177:1: error: 'lightStatus_t' does not name a type

 lightStatus_t           lightStatus;

 ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\aquacontrol32.ino: In function 'void setup()':

aquacontrol32:234:33: error: no matching function for call to 'Adafruit_ILI9341::begin(int, SPIClass&)'

   tft.begin( TFT_SPI_CLOCK, SPI );

                                 ^

In file included from C:\Users\Tom\Documents\Arduino\aquacontrol32\aquacontrol32.ino:7:0:

C:\Users\Tom\Documents\Arduino\libraries\Adafruit_ILI9341/Adafruit_ILI9341.h:131:17: note: candidate: virtual void Adafruit_ILI9341::begin(uint32_t)

         void    begin(uint32_t freq=0);

                 ^

C:\Users\Tom\Documents\Arduino\libraries\Adafruit_ILI9341/Adafruit_ILI9341.h:131:17: note:   candidate expects 1 argument, 2 provided

C:\Users\Tom\Documents\Arduino\aquacontrol32\dimmertask.ino: In function 'void dimmerTask(void*)':

dimmertask:42:3: error: 'lightStatus' was not declared in this scope

   lightStatus = LIGHTS_AUTO;

   ^

dimmertask:42:17: error: 'LIGHTS_AUTO' was not declared in this scope

   lightStatus = LIGHTS_AUTO;

                 ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\dimmertask.ino: In function 'void lightsOn()':

dimmertask:137:3: error: 'lightStatus' was not declared in this scope

   lightStatus = LIGHTS_ON;

   ^

dimmertask:137:17: error: 'LIGHTS_ON' was not declared in this scope

   lightStatus = LIGHTS_ON;

                 ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\dimmertask.ino: In function 'void lightsOff()':

dimmertask:148:3: error: 'lightStatus' was not declared in this scope

   lightStatus = LIGHTS_OFF;

   ^

dimmertask:148:17: error: 'LIGHTS_OFF' was not declared in this scope

   lightStatus = LIGHTS_OFF;

                 ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\dimmertask.ino: In function 'void lightsAuto()':

dimmertask:153:3: error: 'lightStatus' was not declared in this scope

   lightStatus = LIGHTS_AUTO;

   ^

dimmertask:153:17: error: 'LIGHTS_AUTO' was not declared in this scope

   lightStatus = LIGHTS_AUTO;

                 ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\tfttask.ino: In function 'void showMenu()':

tfttask:155:10: error: 'lightStatus_t' does not name a type

   static lightStatus_t displayedLightStatus;

          ^

tfttask:168:5: error: 'displayedLightStatus' was not declared in this scope

     displayedLightStatus = lightStatus;

     ^

tfttask:168:28: error: 'lightStatus' was not declared in this scope

     displayedLightStatus = lightStatus;

                            ^

tfttask:181:8: error: 'displayedLightStatus' was not declared in this scope

   if ( displayedLightStatus != lightStatus )

        ^

tfttask:181:32: error: 'lightStatus' was not declared in this scope

   if ( displayedLightStatus != lightStatus )

                                ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\tfttask.ino: In function 'void showStatus()':

tfttask:233:10: error: 'lightStatus_t' does not name a type

   static lightStatus_t displayedLightStatus;

          ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\tfttask.ino: In function 'void drawMenuButtons()':

tfttask:431:24: error: 'lightStatus' was not declared in this scope

   tempButton.color = ( lightStatus == LIGHTS_ON ) ? ILI9341_RED : ILI9341_BLUE;

                        ^

tfttask:431:39: error: 'LIGHTS_ON' was not declared in this scope

   tempButton.color = ( lightStatus == LIGHTS_ON ) ? ILI9341_RED : ILI9341_BLUE;

                                       ^

tfttask:435:39: error: 'LIGHTS_OFF' was not declared in this scope

   tempButton.color = ( lightStatus == LIGHTS_OFF ) ? ILI9341_RED : ILI9341_BLUE;

                                       ^

tfttask:439:39: error: 'LIGHTS_AUTO' was not declared in this scope

   tempButton.color = ( lightStatus == LIGHTS_AUTO ) ? ILI9341_RED : ILI9341_BLUE;

                                       ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\webservertask.ino: In lambda function:

webservertask:293:67: error: 'lightStatus' was not declared in this scope

       response->printf( "%s\n%s\n", timeStr, lightStatusToString( lightStatus ) );

                                                                   ^

C:\Users\Tom\Documents\Arduino\aquacontrol32\webservertask.ino: In lambda function:

webservertask:462:68: error: 'lightStatus' was not declared in this scope

       return request->send( 200, HTML_HEADER, lightStatusToString( lightStatus ) );

                                                                    ^

webservertask:462:82: error: return-statement with a value, in function returning 'void' [-fpermissive]

       return request->send( 200, HTML_HEADER, lightStatusToString( lightStatus ) );

                                                                                  ^

webservertask:468:68: error: 'lightStatus' was not declared in this scope

       return request->send( 200, HTML_HEADER, lightStatusToString( lightStatus ) );

                                                                    ^

webservertask:468:82: error: return-statement with a value, in function returning 'void' [-fpermissive]

       return request->send( 200, HTML_HEADER, lightStatusToString( lightStatus ) );

                                                                                  ^

webservertask:474:68: error: 'lightStatus' was not declared in this scope

       return request->send( 200, HTML_HEADER, lightStatusToString( lightStatus ) );

                                                                    ^

webservertask:474:82: error: return-statement with a value, in function returning 'void' [-fpermissive]

       return request->send( 200, HTML_HEADER, lightStatusToString( lightStatus ) );

                                                                                  ^

Multiple libraries were found for "SSD1306.h"
 Used: C:\Users\Tom\Documents\Arduino\libraries\ESP8266_and_ESP32_Oled_Driver_for_SSD1306_display
 Not used: C:\Users\Tom\Documents\Arduino\libraries\esp8266-oled-ssd1306-3.2.5
 Not used: C:\Users\Tom\Documents\Arduino\libraries\arduino_880236
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\Tom\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\libraries\WiFi
 Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.15.0_x86__mdqgnx93n4wtt\libraries\WiFi
exit status 1
use of enum 'lightStatus_t' without previous declaration

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

Please advise.

**Comment by CelliesProjects** [comment]
I will look into this.

-EDIT: Looked at it and maybe a simple fix is to install Arduino 1.8.5. and use that for now.

I could not replicate your issue because I don't have a win10 pc, but after updating from Arduino 1.8.5 to 1.8.6 or 1.8.7 on my Linux development pc I got comparable error messages.

**Comment by CelliesProjects** [comment]
This issue should be fixed with 12f425399c4a6f3f1bfe6d100e0aef7247627ed6.
Still no W10 pc to test this, so some feedback would be welcome.

**Comment by tatasker** [comment]
I will get to it later today.

**Comment by CelliesProjects** [comment]
Just tested it on a borrowed W10 laptop and https://github.com/CelliesProjects/aquacontrol32/commit/12f425399c4a6f3f1bfe6d100e0aef7247627ed6 seems to work fine.

**Comment by CelliesProjects** [comment]
The error 
```
C:\Users\Tom\Documents\Arduino\aquacontrol32\aquacontrol32.ino: In function 'void setup()':

aquacontrol32:234:33: error: no matching function for call to 'Adafruit_ILI9341::begin(int, SPIClass&)'

tft.begin( TFT_SPI_CLOCK, SPI );
```
is because the ILI9341 library you are using is not the correct version.
Check [ your included libs](https://github.com/CelliesProjects/aquacontrol32/blob/master/libraries.md ).

**Comment by tatasker** [comment]
Thank you I am going to test it as soon as I can get to it.
